sudo: required
services:
  - docker

before_install:
  - docker build -t nsuscevic/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true nsuscevic/react-test npm test
  
after_success:
  - docker build -t nsuscevic/multi-client ./client
  - docker build -t nsuscevic/multi-nginx ./nginx
  - docker build -t nsuscevic/multi-server ./server
  - docker build -t nsuscevic/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push nsuscevic/multi-client
  - docker push nsuscevic/multi-nginx
  - docker push nsuscevic/multi-server
  - docker push nsuscevic/multi-worker
deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-939903430125
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY        